name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust Toolchain Components
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt
          override: true
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --all -- --check